FROM python:3.7
ENV PYTHONBUFFERED 1

COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt &&\
    rm /requirements.txt
COPY ./server.py /server.py
EXPOSE 8080

CMD python /server.py
