FROM python:3.7
ENV PYTHONBUFFERED 1

COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt &&\
    rm /requirements.txt
COPY ./logger.py /logger.py

CMD python /logger.py
